### PR TITLE
Get all images in multiple image tweet

### PR DESCRIPTION
**Pull request by mizfeng**
1. Change the file name to datetime.
It might differ from different timezone for the original timestamp is for UTC time. This change makes me find a specific image based on pages easily.

2. Get all images in multiple image tweets.
The first image name will be just the datetime and the followed will add the "_n", which n represents the number.

3. Get thumbnails from videos?
After checking the pages, I found the API will return some tweets without the media.
After adding the "tweet_mode" = "extended" and it can get those missing images.
Furthermore, it also gets the thumbnails of videos.

### CODE REVIEW

**Comment by mizfeng** [comment]
1. 更改檔案名稱從unix timestamp為時間，單純方便人工查找跟閱讀
2. 當一則Tweet有多張圖片時，取得所有圖片，命名方式為：第一張為時間，第二張之後會加 "_n"，而n代表第幾張。
3. 新增影片的縮圖。
為什麼會修改這一點是因為發現API回傳時會有一些Tweet明明有圖片，但是並沒有夾帶回傳，而且查找document無果，碰巧看到有人使用者個參數解決其他API的問題，就嘗試加進去，結果不但圖片有回傳，影片縮圖也有回傳，所以算是解決一個問題附帶增加一個feature:D

**Comment by mizfeng** [comment]
This program is very useful and makes me don't have to save any image one by one.
It seems that I don't know much about how the "fork" function works. I originally just want to make a version on my branch so I might change some features just for myself, like the filename.
I've tested and compared the result to the pages which are shown on the browser. Hope some feature is useful.

**Comment by morinokami** [comment]
@jimy811111 
Great (太好了)! I confirmed that your code works well. Thanks for your contribution.

**Comment by mizfeng** [comment]
It's my pleasure to attend this useful project. :D

**Pull request merged**
